[package]
name = "vqf-rs"
version = "2.0.0"
edition = "2021"

[dependencies]
nalgebra = { version = "0.32", default-features = false, features = ["libm"] }
serde = { version = "1.0.152", features = ["derive"] }
serde_json = "1.0.91"
vqf = { path = "SlimeVR-Rust/vqf" }
